### ISSUE TITLE
Criar template para checklist de benefícios de patrocínio

### ISSUE THREAD

**Issue by alynnefs** [pythonbrasil/pybr2021-org#138]
### Descrição
Criar template com uma lista de verificação dos benefícios de cada patrocinador

### Requisitos para a atividade ser considerada como concluída

- template criado

**Comment by cecivieira** [comment]
@tiidadavena tu poderia fazer esse checklist pra @deboraazevedo Comunicação colocar isso no cronograma?

**Comment by tiidadavena** [comment]
Posso sim!

Só não entendi muito bem sobre o que deve ter nesse doc: seriam os benefícios para cada patrocinador confirmado (ex: benefícios da JusBrasil) ou seria mais um cronograma de atividades mais genéricas com a entrega prevista de atividades?

**Comment by cecivieira** [comment]
Acho que tu pode fazer um checklist genérico aqui (e fechar essa issue), além disso a cada nova empresa com contrato fechado tu abre uma issue com template de ARTE informando a empresa e coloca o checklist lá.

Esse template já atribue  a atividade a @deboraazevedo e Camila.

**Comment by alynnefs** [comment]
O formulário foi feito, mas se compartilhar o link pode ser que alguém não autorizado responda, mesmo que não tenha permissão pra editar. Vou fechar a issue. Se vocês pensarem em algo pra "comprovar" que foi feito, fiquem à vontade pra reabrir (:

**Comment by cecivieira** [comment]
Checklists:

**Ouro**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [ ] Exposição da marca durante toda a grade de palestra (background do StreamYard)
- [ ] Apresentação do vídeo institucional na abertura das Keynote
- [ ] Post nas redes sociais antes do evento
- [ ] Post nas redes sociais durante o evento
- [ ] Post nas redes sociais pós evento
- [ ] Post nas redes sociais com vídeo da patrocinadora
- [ ] Job fair
- [ ] Tutorial
- [ ] Canal exclusivo no Discord
- [ ] Exposição da marca em toda comunicação via e-mail para participantes e facilitadoras de atividades

**Prata**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Exposição da marca na abertura das palestras (versão final do vídeo a ser upado para o youtube)
- [ ] Post nas redes sociais antes do evento
- [ ] Post nas redes sociais durante o evento
- [ ] Post nas redes sociais pós evento
- [ ] Job fair
- [ ] Tutorial
- [ ] Canal exclusivo no Discord

**Bronze**
- [ ] Agradecimento no início de cada dia de evento
- [ ] Exposição da marca no site
- [ ] Exposição da marca durante os intervalos das palestras
- [ ] Post nas redes sociais antes do evento
- [ ] Post nas redes sociais durante o evento
- [ ] Post nas redes sociais pós evento
