### ISSUE TITLE
[Reunião] Geral: 10 maio 2021

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2021-org#28]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêncide no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião Geral

- Data: 10 maio 2021 
- Participantes:
  - Ana Cecília Vieira (@cecivieira)
  - Alynne Ferreira (@alynnefs)
  - Andre Pastore (@apast)
  - Camila Alves (@cmdiasbr)
  - Débora Azevedo (@deboraazevedo)
  - Marco Rougeth (@rougeth)
  - Ana Dulce (@anadulce)
  - Gislene Vanessa Lima (@martinsvanessa)
  - Gabriel Bellon (@gabubellon)

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Acompanhamento das ações pendentes da última reunião

Atividade| Responsável | Link útil| Observações|
--| --| --|--|

### Itens a serem debatidos

- [x] [Data do evento](https://github.com/pythonbrasil/pybr2021-org/issues/2)
Opções: 11 a 17 de outubro / 01 a 07 novembro
Em meados de outubro ou início de novembro.

- [x] [Patrocínio](https://github.com/pythonbrasil/pybr2021-org/issues/9)
* Adicionar números de participantes e afins na proposta de patrocínio
* Cotas:
    * Definir cotas diferentes para cada tipo de patrocinador: uma para empresa interessada em recrutação e outra para empresa interessada em divulgar produto;
    * Pensar em modelos de interações entre participantes que querem divulgar produto;
    * Possível interação entre participantes e palestrantes e definir "preço" nisso;
* Levantar custo com: 
    * Intérprete de Libra;
    * Tradução simultânea;
    * Ferramenta de Stream (StreamYard);
    * Custo Operacional;
    
- [x] [Tema para arte do evento](https://github.com/pythonbrasil/pybr2021-org/issues/29)
Mandar ideias de forma assíncrona no grupo

- [ ] [Definir formato do evento](https://github.com/pythonbrasil/pybr2021-org/issues/6)
Será definido posteriormente

- [x] Definir canal de comunicação da organização
     * Vamos utilizar o telegram como canal sincrono de comunicação
     * Vamos utilizar as [issues](https://github.com/pythonbrasil/pybr2021-org/issues) do github como canal assincrono
     * Caso começamos a perder informação ou ter ruídos de comunicação, rediscutimos esse ponto

### Ações para serem realizadas

Atividade| Responsável | Link útil| Observações|
--| --| --|--|
Procurar possíveis eventos conflitantes | @alynnefs, @deboraazevedo| #30 | --|
Reunião de patrocínio com JusBrasil| @alynnefs| #40|--|
Arte para divulgação da Big Kahuna| @cmdiasbr| #31|--|
Cotar Intérprete de Libra| @gabubellon, @alynnefs | #33| --|
Cotar Tradução simultânea| @alynnefs| #34| --|
Cotar Ferramenta de Stream (StreamYard)| @cecivieira| #35|--|
Cotar Custo Operacional| @gabubellon | #36|--|
Ler e divulgar os feedbacks da pybr2020 | @cecivieira, @anadulce, @rougeth, @alynnefs | #32 |--|
Anunciar Python Brasil online e Alynne como Big Kahuna | @anadulce,  @rougeth | #7 |
Pensar em modelos de interações entre patrocinadores que querem divulgar produto | --| #38| --|
Possível interação entre participantes e palestrantes e definir "preço" nisso | --| #39| --|

### Próxima reunião
https://github.com/pythonbrasil/pybr2021-org/issues/37

**Comment by gabubellon** [comment]
https://github.com/pythonbrasil/pybr2021-org/issues/30
